package net.yamac.springboot2.example;

import static org.assertj.core.api.Assertions.fail;

import org.junit.Test;

import lombok.Builder;

public class LombokApplyTest {
    @Builder
    private static class Target {
    }

    @Test
    public void testLombokIsEnabledInTestScope() {
        try {
            Target.class.getMethod("builder");
        } catch (NoSuchMethodException e) {
            fail("builder method not generated by Lombok. Test FAILED", e);
        }
    }
}
