---
spring.profiles: local
spring.profiles.include: common-local
---
spring.profiles: local-test
spring.profiles.include: common-local,common-local-test
---
spring.profiles: beta
spring.profiles.include: common-beta
---
spring.profiles: beta-test
spring.profiles.include: common-beta,common-beta-test
